#pragma once

enum REQUEST_CODES
{
    CODE_MIN = 0xDEADBEEF,

    CODE_INITIALIZE,
    CODE_ALLOCATE_MEMORY,
    CODE_FREE_MEMORY,
    CODE_WRITE_MEMORY,
    CODE_READ_MEMORY,
    CODE_CHANGE_MEMORY_PROTECTION,
    CODE_GET_MODULE_HANDLE,
    CODE_GET_PROCESSID,

    CODE_MAX
};